### ISSUE TITLE
Wait until it converts

### ISSUE THREAD

**Issue by Lcampos85** [eliangerard/text-to-mp3#3]
The library so far seems to be very good, I would just like to know if you know the approximate time it takes to convert the file to mp3 and / or is there a function with promises or async/await to wait until it finishes converting.

Thanks

**Comment by eliangerard** [comment]
Thank you for your feedback! I'll be working on updating this package in the next few days. I'll create both async and sync versions of every method and add some extra features. I apologize for taking so long to respond, but I was deciding what to do and finding some time. Thanks again!
